
---
run_config:
 n_envs: 8
 policy_type: MlpPolicy
 total_timesteps: 1.0e+6
 n_steps: 2^11
 batch_size: 2^6
 vf_coef: 0.5
 ent_coef: 0.25
 gamma: 0.8
 evaluate_on_validation_set: True
 max_number_of_steps: 50
 render_on_evaluation: False
 deterministic: True
 use_action_masks: False
 dataset_path: prompts/big_dataset/prompts.csv
 embeddings_path: prompts/big_dataset/embeds/llama/llama-2/llama-2-7b-f16.bin
 embedding_size: 4096
 random_state: 42
 models_save_path: ./models/tests
 logs_save_path: ./logs/tests

policy_kwargs:
 net_arch:
    pi:
    - 256
    - 256
    vf:
    - 256
    - 256
 activation_fn: ReLU

env_config:
 env_id: WilsonMaze-v0
 render_mode: text
 size: 7
 timelimit: 30
 random_seed: 42
 variable_target: False
 add_coins: True
 terminate_on_wrong_target: True
 prompt_size: 1024
 prompt_mean: True
...