
---
run_config:
 n_envs: 8
 policy_type: MlpPolicy
 total_timesteps: 1.0e+6
 n_steps: 2^12
 batch_size: 2^6
 evaluate_on_validation_set: True
 max_number_of_steps: 15
 render_on_evaluation: False
 deterministic: True
 use_action_masks: True
 dataset_path: prompts/big_dataset/prompts.csv
 embeddings_path: prompts/big_dataset/llama/llama-2-7b-f16-mean-out.bin
 embedding_size: 4096
 random_state: 42
 models_save_path: ./models/tests-3
 logs_save_path: ./logs/tests-3

policy_kwargs:
 net_arch:
    pi:
    - 256
    - 128
    vf:
    - 256
    - 128
 activation_fn: ReLU

env_config:
 id: WilsonMaze-v0
 render_mode: text
 size: 7
 timelimit: 30
 random_seed: 42
 number_of_targets: 4
 add_coins: True
 terminate_on_wrong_target: True
 prompt_size: 1024
 prompt_mean: False
...