
---
run_config:
 n_envs: 8
 policy_type: MlpPolicy
 total_timesteps: 3.0e+6
 n_steps: 2^11
 batch_size: 2^6
 vf_coef: 1
 ent_coef: 0.2
 gamma: 0.9
 clip_range: 0.2
 max_grad_norm: 0.5
 evaluate_on_validation_set: True
 max_number_of_steps: 50
 render_on_evaluation: False
 deterministic: True
 use_action_masks: False
 dataset_path: prompts/big_dataset/prompts.csv
 embeddings_path: prompts/big_dataset/embeds/phi/phi-1.5/phi-1-5-f16.bin
 embedding_size: 2048
 random_state: 42
 models_save_path: ./models/phi/phi-1-5
 logs_save_path: ./logs/phi/phi-1-5

policy_kwargs:
 net_arch:
    pi:
    - 256
    - 256
    vf:
    - 256
    - 256
 activation_fn: elu

env_config:
 env_id: WilsonMaze-v0
 render_mode: text
 size: 7
 timelimit: 10
 random_seed: 42
 variable_target: False
 add_coins: True
 terminate_on_wrong_target: True
 prompt_size: 1024
 prompt_mean: True
...